spring.application.name=Inicio


# CONFIGURACIÓN DEL SERVIDOR

server.port=8081

# CONFIGURACIÓN BASE DE DATOS MYSQL

spring.datasource.url=jdbc:mysql://localhost:3307/inventario2
spring.datasource.username=root
spring.datasource.password=

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN JPA (HIBERNATE)

# update = crea/actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Evitar problemas con transacciones
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPatform

#Definir la aplicación como apliación web servelet
spring.main.web-application-type=servlet